install:
 - mvn clean
script:
 - mvn -B -Pall test -Dversion.org.jboss.wildfly.dist=11.0.0.CR1
language: java
jdk:
  - oraclejdk8
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
